name: PikaShop
version: 1.0.0
main: vn.pika.pikashop.PikaShop
api-version: 1.21
author: PikaMC
description: Shop rieng cua PikaMC (shop 2 buoc, sell tha do, multiplier, shard v2)
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  pshop:
    description: Mo menu shop chinh (PikaShop)
    usage: /pshop
  psell:
    description: Mo GUI ban do (PikaShop)
    usage: /psell
  psellmulti:
    description: Xem tien trinh multiplier (PikaShop)
    usage: /psellmulti
  psellhistory:
    description: Xem lich su ban (PikaShop)
    usage: /psellhistory
  pworth:
    description: Xem gia tri vat pham (PikaShop)
    usage: /pworth
  pshard:
    description: Tien Shard (PikaShop v2)
    usage: /pshard <balance|pay|shop|top|afk>
  pikashop:
    description: Lenh admin PikaShop
    usage: /pikashop reload
    permission: pikashop.admin
permissions:
  pikashop.use:
    description: Dung shop/sell co ban
    default: true
  pikashop.admin:
    description: Admin PikaShop
    default: op
  pikashop.shard.extra_ten:
    description: Bonus shard khi giet (+10)
    default: false
  pikashop.shard.extra_twenty:
    description: Bonus shard khi giet (+20)
    default: false
